---
ID: "1ba222e4-fc27-4a48-93d3-a8be3aaa5c62"
Parent: "cdc527bc-d2c1-441b-b45e-f22be30f9262"
Template: "99f8905d-4a87-4eb8-9f8b-a9bebfb3add6"
Path: /sitecore/layout/Renderings/Cookbook/Product List
DB: master
SharedFields:
- ID: "3d08db46-2267-41b0-bc52-be69fd618633"
  Hint: Cacheable
  Type: Checkbox
  Value: 1
- ID: "51b435bc-f7b9-478a-9c51-52916af96ff5"
  Hint: Path
  Value: /Views/Content/ProductList.cshtml
- ID: "8b6d532b-6128-4486-a044-ca06d90948ba"
  Hint: VaryByData
  Type: Checkbox
  Value: 1
- ID: "ddab263e-b42e-419a-aa6f-081b7393ca38"
  Hint: Model
  Value: /sitecore/layout/Models/Cookbook/ItemList
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181005T111909Z
