---
ID: "276c3722-1697-44cf-ac67-1a49d017acc2"
Parent: "4da0a8dd-18c9-4b2e-bc38-a9e4effdaa86"
Template: "00a984ab-24d2-450a-be90-38e12c1e5b5c"
Path: /sitecore/content/Global/Configurations
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181004T112327Z
    - ID: "70bb4926-1f63-4f23-8948-c1b449f1921d"
      Hint: Copyright Text
      Value: |
        Copyright 2018
        Colours BV
        
