---
ID: "8d678e1e-6463-41a6-a749-658bacd0c58e"
Parent: "45b5941a-a719-4bad-87f6-8d75af1cc6f8"
Template: "793e5141-df00-4847-9d25-d957d1df466a"
Path: /sitecore/content/Home/Products
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181004T114127Z
    - ID: "c32abd0d-3cfc-460e-b011-d10416d0b994"
      Hint: Title
      Value: Products
    - ID: "fddbad72-be6a-4d7c-ba15-788d9e4438d5"
      Hint: Body
      Value: These are the products
- Language: "es-ES"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181005T120109Z
    - ID: "33700c77-3cd4-40d2-8fb1-70d051705f88"
      Hint: Show in Menu
      Type: Checkbox
      Value: 1
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "c32abd0d-3cfc-460e-b011-d10416d0b994"
      Hint: Title
      Value: Spanish Products
    - ID: "fddbad72-be6a-4d7c-ba15-788d9e4438d5"
      Hint: Body
      Value: Si
