---
ID: "93f4b4ab-da10-4e76-b64b-d862f22afdbc"
Parent: "c6f57bd9-a4e9-4667-8e57-94aefca4614d"
Template: "c6f57bd9-a4e9-4667-8e57-94aefca4614d"
Path: /sitecore/templates/Cookbook/Comment/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181009T075726Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
